version: "3.8"

services:
  healthchecks-front:
    build:
      context: .
      target: production
      args:
        NEXT_PUBLIC_APIKEY: ${NEXT_PUBLIC_APIKEY}
        NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
    ports:
      - "3000:3000"
    restart: unless-stopped
